### ISSUE TITLE
当服务端 context-path 不为默认时，页面导航请求逻辑待优化

### ISSUE THREAD

**Issue by louis-zhou** [rocketmq/rocketmq-console-ng#23]
当server.context-path不为默认值时，页面所有js/css/ajax请求等路径都需要修改

**Comment by StyleTang** [comment]
Yes, it is.thanks you~
Could you fix it for us, and send a pull request.
:-)

**Comment by StyleTang** [comment]
I had enhanced it.
So I close this issue.
Thanks for your issue :-)
